version: "3"
services:
  casplit-backend:
    build: .
    image: casplit-node
    depends_on:
      - mongo-db
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /app/node_modules # anonymous volume
    environment:
      - PORT=8000
      - MONGO_USER=root
      - MONGO_PASSWORD=root
      - NODE_ENV=development
      - MONGO_IP=mongo-db
      - MONGO_PORT=27017
    env_file:
      - ./.env

    command: npm run dev

  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    container_name: mongo-db-casplit-container
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo-db:27017/

volumes:
  mongo-db:
