version: "3"
services:
  casplit-frontend:
    build: .
    image: casplit-react
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env.development.local
